# Generated by Django 2.1.9 on 2020-05-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='useres',
            fields=[
                ('Nickname', models.CharField(blank=True, max_length=50)),
                ('Full_Name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('phone_no', models.CharField(blank=True, max_length=15)),
                ('password', models.CharField(max_length=70)),
                ('img', models.ImageField(default='user_pic/icon.png', upload_to='user_pic')),
                ('Description', models.TextField(blank=True, default='Add Your Description')),
                ('Social_link', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'db_table': 'useres',
            },
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('ShopName', models.CharField(max_length=100)),
                ('ShopCategory', models.CharField(max_length=100)),
                ('OwnerName', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Phone', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=200)),
                ('Landmark', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Description', models.TextField(blank=True, default='Add Your Description')),
                ('Social_link', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'db_table': 'Vendors',
            },
        ),
    ]
